syntax on
colorscheme industry

set relativenumber
set wildmenu		" display completion matches in a status line

set showcmd
set ruler
set showmode

set encoding=utf-8
set fileencoding=utf-8

set colorcolumn=75,80

set mouse=
set nocompatible
set backspace=indent,eol,start  " more powerful backspacing
set autoindent
